Block 3 Lesson 1 Release
kingnsk/GeekBrains pull request #16
Opened 2021-03-22 17:35 UTC by kingnsk

2021-03-22 21:02 UTC, Forkosigan requested changes

2021-03-22 21:02 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +        public IActionResult Create([FromQuery] string temperature, [FromQuery] DateTime? timeMeasure)
temperature не string а сразу int. А если хочется сделать проверку на наличие входного параметра, то int?

2021-03-22 21:02 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +
лишние пустые строки после { читаемости не добавляют

2021-03-22 21:02 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +                return BadRequest();
а почему BadRequest. Если не задано начальное значение то можно вернуть все <= конечного и тоже самое верно для не заданного конечного интервала

2021-03-22 21:02 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +            var tempValues=new List<WeatherForecast>();
что значит temp? Это сокращение от температуры? или это temp от английского временный. Если от температуры,то забудьте о сокращениях  - ни в каких языках программирования они не приветсвуются

2021-03-22 21:02 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +            foreach (var dataT in holder.Values)
что такое dataT? нужно понятное читемое имя

2021-03-22 21:02 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +        public IActionResult Update([FromQuery] string timeToUpdate, [FromQuery] string newTemperature)
Зачем тут оба параметра string? Один DateTime. Другой int

2021-03-22 21:02 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +                    holder.Values.RemoveAt(i);
Это приведет к ошибке. Нельзя исключать из коллекции, по которой итерируем через foreach элементы. Это как раз тот случай когда foreach так вот прямо использовать нельзя

2021-03-23 15:35 UTC, kingnsk commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +        public IActionResult Create([FromQuery] string temperature, [FromQuery] DateTime? timeMeasure)
Согласен. Fixed.

2021-03-23 15:35 UTC, kingnsk commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +
fixed.

2021-03-23 15:35 UTC, kingnsk commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +                return BadRequest();
Логика не была явно задана в задании, решил что пользователь обязан передать оба значения. Если переделать, получится более гибкое решение...

2021-03-23 15:35 UTC, kingnsk commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +            var tempValues=new List<WeatherForecast>();
Подразумевал temp = temporary, переименовал в selectedValues чтоб избежать двойственности при чтении кода.

2021-03-23 15:35 UTC, kingnsk commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +            foreach (var dataT in holder.Values)
fixed.

2021-03-23 15:35 UTC, kingnsk commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +        public IActionResult Update([FromQuery] string timeToUpdate, [FromQuery] string newTemperature)
fixed.

2021-03-23 15:35 UTC, kingnsk commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +                    holder.Values.RemoveAt(i);
В таком случае правильно использовать цикл, например for?

2021-03-24 12:35 UTC, Forkosigan requested changes

2021-03-24 12:35 UTC, Forkosigan commented on Block3/bl3_less1/MetricsManager/Controllers/CrudController.cs
> +                    holder.Values.RemoveAt(i);
тут целый спектр. Можно for, можно просто синтаксический сахар в виде RemoveAll (есть такой метод у List)

2021-03-31 15:52 UTC, merged